Fix: Parsing for colliding column values
Large exponents in the MESS output can fill up a column width, so there is no
space between two kT values. This was causing errors like the following,
because we were relying on str.split() to break up the row:
```
ValueError: could not convert string to float: '2.64e-13-2.62e+200'
```
This is now fixed by using pyparsing_common.number.